config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words
 
  
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/about'
  root 'home#index'
  
  get '/words', to: 'word#index'
  post '/word', to: 'word#new'
  get '/error', to: 'word#error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: %i[ show edit update destroy ]

  # GET /words or /words.json
  def index
    @words = Word.all
  end
  def error; end

  # GET /words/1 or /words/1.json
  def show
    @word = Word.find_by(id: params[:id])

  end

  # GET /words/new
 
  def new
    @word = Word.find_by(name: params[:q])
    if @word
      redirect_to action: "show", id: @word.id
    else
      if DictionarySearch.new(word_params).call
        @word = DictionarySearch.new(word_params).call
        redirect_to action: "show", id: @word.id
      else
        redirect_to error_path
      end
    end
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words or /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to word_url(@word), notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to word_url(@word), notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:word, :definition, :tags)
      params.permit(:endpoint, :q, :authenticity_token, :commit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Dictionary', root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "About the App", home_about_path, class: "nav-link" %>
        
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About the app </h1>

app/views/home/index.html.erb
<h1>DICTIONARY APP</h1>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <%= render "layouts/navigation/header" %>
      </div>
      <div class="col-sm-5">
        <%= render "layouts/navigation/collapsible_elements" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" 
      type="image/png" 
      href="https://www.oed.com/assets/ctx/20200924/images/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dictionary App</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Biryani:200,400&display=swap">
    <% if !Rails.env.test? %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Biryani:200,400&display=swap">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <% end %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  	<%= render "layouts/navigation" %>
    <%= yield %>
  </body>

  <footer class="footer font-small blue pt-4">
    <div class="footer-copyright text-center py-3"> 2020 Copyright:
    </div>
  </footer>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word, style: "display: block" %>
    <%= form.text_field :word %>
  </div>

  <div>
    <%= form.label :definition, style: "display: block" %>
    <%= form.text_field :definition %>
  </div>

  <div>
    <%= form.label :tags, style: "display: block" %>
    <%= form.text_field :tags %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/words/_word.html.erb
<div id="<%= dom_id word %>">
  <p>
    <strong>Word:</strong>
    <%= word.word %>
  </p>

  <p>
    <strong>Definition:</strong>
    <%= word.definition %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= word.tags %>
  </p>

</div>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Show this word", @word %> |
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/error.html.erb
<div class='container p-3 my-3 border'>
  <div class="card">
    <h1>Something went wrong, please check the spelling and try again.</h1>
      <% if flash[:notice] %>
        <div class="alert alert-warning"><%= flash[:notice] %></div>
      <% end %>
    <div class="container p-3 my-3 border">
      <%= form_tag("/word", method: "post") do %>
        <%= select_tag "endpoint", options_for_select([ "Oxford" ], "Oxford") %>
        <%= label_tag(:q, "") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>
 </div>

app/views/words/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Words</h1>

<h1>The last 5 searched words:</h1>
<div class="card">
  <ol>
    <%@words.each do |word| %>
      <li><%= link_to word.name, word_path+"/#{word.id}" %></li>
    <%end%>
  </ol>
</div>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Results:</h1>
<div class="card">
  <h2><%= @word.name %></h2>
  <p><%= @word.definition %></p>
  <br>
  <p><%= link_to "Last 5 words", words_path %></p>
</div>